language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=origin/2.0

before_script:
  - pyrus install --force phpunit/DbUnit
  - php vendor/vendors.php

script: phpunit --coverage-text

notifications:
  email:
    - travis-ci@kitpages.fr
