language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=origin/master

before_script:
  - pear channel-discover pear.phpunit.de
  - pear install pear install phpunit/DbUnit
  - vendor/vendors.php

notifications:
  email:
    - travis-ci@kitpages.fr
